name: Auto merge
on: pull_request
jobs:
  showenv:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTOR: ${{ github.actor }}    
    steps:
      - name: Show env
        run: echo "${GITHUB_ACTOR}"
  merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:                                 # マージに必要なパーミッション
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub CLIのクレデンシャル
    steps:
      - uses: actions/checkout@v4
      - run: gh pr merge "${GITHUB_HEAD_REF}" --merge # GitHub CLIでマージ