name: Secrets
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            PASSWORD: ${{ secrets.PASSWORD }}
        steps:
            - run: echo "${PASSWORD}"
            - run: echo "${PASSORD:0:1} ${PASSWORD#?}"